language: node_js
node_js:
  - '0.10'
before_script:
  - rm -rf node_modules
  - rm -fr game
  - npm install
  - npm install -g grunt-cli
  - git config --global user.name "travis-ci"
  - git config --global user.email "sircapsalot@gmail.com"

env:
  global:
    secure: dL2QiBilmnq+EGKcyEpIAHTPM/ff70qpH9gA5nsHGySRv1MVAA+KOyDuYXFOwdGtj7pRWAd+GF6GrYIAJQmTv0schDMn7W4wC5EU5bh5oeWxX1y+XpDVyxdqtDETn35QG2V+uyS+ux8Iu0CTGe4dHgquciE1+9tF8xX/QuSVelc=

after_script:
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - git add game
  - git commit -m "Release"
  - git push