language: node_js
node_js:
- '0.10'
rvm:
- 2.1.0
before_install:
- gem install haml
- gem install compass
before_script:
- 'echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config' # this is a workaround for pushing to github until the RSA fingerprint is added.
- git config --global user.name "travis-ci"
- git config --global user.email "sircapsalot@gmail.com"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- git config credential.helper "store --file=.git/credentials"
- git checkout master
- rm -fr game
- git add -A game
- git commit -m "Removing previous version."
- node ./node_modules/grunt-cli/bin/grunt
after_script:
- git remote rm origin
- git remote add origin git@github.com:ddavison/dot-hunt.git
- git add -A game
- git commit -m "Release."
- git push -u origin master

env:
  global:
    secure: vsKWJU74S4t0Qbdf9yQaVG/dPmllCyiaWWMBul8tx4d6yZZB7CoKQ11p+DHhP0JOJRBgX/ZYJbbBuxniG6rWyuoEuWeFNyOO3ZApal7/R3A8Cnuo6wSa2V2DC1Cl6d5cDtJ3LBXcCQSDd2GAdKd3FglFYNTab2SJJWT4M2dmYvI=
